//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public long Empid { get; set; }
        public string EmpName { get; set; }
        public string EmpMobileNo { get; set; }
        public string EmpEmailId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> BussinessId { get; set; }
        public Nullable<int> IsEmail { get; set; }
        public Nullable<int> IsCreadential { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
